version: '3'
services:
    jupyroot:
        build: ./
        image: iwng/jupyroot
        container_name: jupyroot
        ports:
            - 8888:8888
        volumes:
            - ./notebook:/home/jovyan/notebook
        working_dir: /home/jovyan/notebook
        command: >
            jupyter-lab --no-browser --port=8888 --ip=0.0.0.0
            --NotebookApp.token='tof'
